package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Ahorro generated by hbm2java
 */
public class Ahorro  implements java.io.Serializable {


     private Integer idahorro;
     private Empleado empleado;
     private String semana;
     private int caja;
     private double porCaja;
     private double porAhorro;
     private double porAporte;
     private double ahoTra;
     private double totalAho;
     private double deposito;

    public Ahorro() {
    }

    public Ahorro(Empleado empleado, String semana, int caja, double porCaja, double porAhorro, double porAporte, double ahoTra, double totalAho, double deposito) {
       this.empleado = empleado;
       this.semana = semana;
       this.caja = caja;
       this.porCaja = porCaja;
       this.porAhorro = porAhorro;
       this.porAporte = porAporte;
       this.ahoTra = ahoTra;
       this.totalAho = totalAho;
       this.deposito = deposito;
    }
   
    public Integer getIdahorro() {
        return this.idahorro;
    }
    
    public void setIdahorro(Integer idahorro) {
        this.idahorro = idahorro;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getSemana() {
        return this.semana;
    }
    
    public void setSemana(String semana) {
        this.semana = semana;
    }
    public int getCaja() {
        return this.caja;
    }
    
    public void setCaja(int caja) {
        this.caja = caja;
    }
    public double getPorCaja() {
        return this.porCaja;
    }
    
    public void setPorCaja(double porCaja) {
        this.porCaja = porCaja;
    }
    public double getPorAhorro() {
        return this.porAhorro;
    }
    
    public void setPorAhorro(double porAhorro) {
        this.porAhorro = porAhorro;
    }
    public double getPorAporte() {
        return this.porAporte;
    }
    
    public void setPorAporte(double porAporte) {
        this.porAporte = porAporte;
    }
    public double getAhoTra() {
        return this.ahoTra;
    }
    
    public void setAhoTra(double ahoTra) {
        this.ahoTra = ahoTra;
    }
    public double getTotalAho() {
        return this.totalAho;
    }
    
    public void setTotalAho(double totalAho) {
        this.totalAho = totalAho;
    }
    public double getDeposito() {
        return this.deposito;
    }
    
    public void setDeposito(double deposito) {
        this.deposito = deposito;
    }




}


