package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ajuste generated by hbm2java
 */
public class Ajuste  implements java.io.Serializable {


     private Integer idAjuste;
     private String concepto;
     private Date ajusFecha;
     private String ajusEmp;
     private Set canAjustes = new HashSet(0);

    public Ajuste() {
    }

	
    public Ajuste(String concepto, Date ajusFecha, String ajusEmp) {
        this.concepto = concepto;
        this.ajusFecha = ajusFecha;
        this.ajusEmp = ajusEmp;
    }
    public Ajuste(String concepto, Date ajusFecha, String ajusEmp, Set canAjustes) {
       this.concepto = concepto;
       this.ajusFecha = ajusFecha;
       this.ajusEmp = ajusEmp;
       this.canAjustes = canAjustes;
    }
   
    public Integer getIdAjuste() {
        return this.idAjuste;
    }
    
    public void setIdAjuste(Integer idAjuste) {
        this.idAjuste = idAjuste;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Date getAjusFecha() {
        return this.ajusFecha;
    }
    
    public void setAjusFecha(Date ajusFecha) {
        this.ajusFecha = ajusFecha;
    }
    public String getAjusEmp() {
        return this.ajusEmp;
    }
    
    public void setAjusEmp(String ajusEmp) {
        this.ajusEmp = ajusEmp;
    }
    public Set getCanAjustes() {
        return this.canAjustes;
    }
    
    public void setCanAjustes(Set canAjustes) {
        this.canAjustes = canAjustes;
    }




}


