package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private Integer idAlm;
     private Camion camion;
     private Producto producto;
     private int cantidad;
     private Set salidas = new HashSet(0);
     private Set canAjustes = new HashSet(0);

    public Almacen() {
    }

	
    public Almacen(Camion camion, Producto producto, int cantidad) {
        this.camion = camion;
        this.producto = producto;
        this.cantidad = cantidad;
    }
    public Almacen(Camion camion, Producto producto, int cantidad, Set salidas, Set canAjustes) {
       this.camion = camion;
       this.producto = producto;
       this.cantidad = cantidad;
       this.salidas = salidas;
       this.canAjustes = canAjustes;
    }
   
    public Integer getIdAlm() {
        return this.idAlm;
    }
    
    public void setIdAlm(Integer idAlm) {
        this.idAlm = idAlm;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }
    public Set getCanAjustes() {
        return this.canAjustes;
    }
    
    public void setCanAjustes(Set canAjustes) {
        this.canAjustes = canAjustes;
    }




}


