package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Can generated by hbm2java
 */
public class Can  implements java.io.Serializable {


     private Integer idcan;
     private DevolucionDes devolucionDes;
     private String proDe;
     private String canDe;
     private String preDevo;

    public Can() {
    }

    public Can(DevolucionDes devolucionDes, String proDe, String canDe, String preDevo) {
       this.devolucionDes = devolucionDes;
       this.proDe = proDe;
       this.canDe = canDe;
       this.preDevo = preDevo;
    }
   
    public Integer getIdcan() {
        return this.idcan;
    }
    
    public void setIdcan(Integer idcan) {
        this.idcan = idcan;
    }
    public DevolucionDes getDevolucionDes() {
        return this.devolucionDes;
    }
    
    public void setDevolucionDes(DevolucionDes devolucionDes) {
        this.devolucionDes = devolucionDes;
    }
    public String getProDe() {
        return this.proDe;
    }
    
    public void setProDe(String proDe) {
        this.proDe = proDe;
    }
    public String getCanDe() {
        return this.canDe;
    }
    
    public void setCanDe(String canDe) {
        this.canDe = canDe;
    }
    public String getPreDevo() {
        return this.preDevo;
    }
    
    public void setPreDevo(String preDevo) {
        this.preDevo = preDevo;
    }




}


