package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * CanAjuste generated by hbm2java
 */
public class CanAjuste  implements java.io.Serializable {


     private Integer idcanAjuste;
     private Ajuste ajuste;
     private Almacen almacen;
     private int cantA;

    public CanAjuste() {
    }

    public CanAjuste(Ajuste ajuste, Almacen almacen, int cantA) {
       this.ajuste = ajuste;
       this.almacen = almacen;
       this.cantA = cantA;
    }
   
    public Integer getIdcanAjuste() {
        return this.idcanAjuste;
    }
    
    public void setIdcanAjuste(Integer idcanAjuste) {
        this.idcanAjuste = idcanAjuste;
    }
    public Ajuste getAjuste() {
        return this.ajuste;
    }
    
    public void setAjuste(Ajuste ajuste) {
        this.ajuste = ajuste;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public int getCantA() {
        return this.cantA;
    }
    
    public void setCantA(int cantA) {
        this.cantA = cantA;
    }




}


