package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer idcargo;
     private String carTra;
     private Set empleados = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String carTra) {
        this.carTra = carTra;
    }
    public Cargo(String carTra, Set empleados) {
       this.carTra = carTra;
       this.empleados = empleados;
    }
   
    public Integer getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(Integer idcargo) {
        this.idcargo = idcargo;
    }
    public String getCarTra() {
        return this.carTra;
    }
    
    public void setCarTra(String carTra) {
        this.carTra = carTra;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


