package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Carga generated by hbm2java
 */
public class Carga  implements java.io.Serializable {


     private Integer idcarga;
     private String tipoCargar;
     private Date feCar;
     private int CVa;
     private String camiCa;

    public Carga() {
    }

    public Carga(String tipoCargar, Date feCar, int CVa, String camiCa) {
       this.tipoCargar = tipoCargar;
       this.feCar = feCar;
       this.CVa = CVa;
       this.camiCa = camiCa;
    }
   
    public Integer getIdcarga() {
        return this.idcarga;
    }
    
    public void setIdcarga(Integer idcarga) {
        this.idcarga = idcarga;
    }
    public String getTipoCargar() {
        return this.tipoCargar;
    }
    
    public void setTipoCargar(String tipoCargar) {
        this.tipoCargar = tipoCargar;
    }
    public Date getFeCar() {
        return this.feCar;
    }
    
    public void setFeCar(Date feCar) {
        this.feCar = feCar;
    }
    public int getCVa() {
        return this.CVa;
    }
    
    public void setCVa(int CVa) {
        this.CVa = CVa;
    }
    public String getCamiCa() {
        return this.camiCa;
    }
    
    public void setCamiCa(String camiCa) {
        this.camiCa = camiCa;
    }




}


