package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Cheque generated by hbm2java
 */
public class Cheque  implements java.io.Serializable {


     private String idcheque;
     private Despacho despacho;
     private double montoChe;
     private boolean staChe;
     private String banco;

    public Cheque() {
    }

    public Cheque(String idcheque, Despacho despacho, double montoChe, boolean staChe, String banco) {
       this.idcheque = idcheque;
       this.despacho = despacho;
       this.montoChe = montoChe;
       this.staChe = staChe;
       this.banco = banco;
    }
   
    public String getIdcheque() {
        return this.idcheque;
    }
    
    public void setIdcheque(String idcheque) {
        this.idcheque = idcheque;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public double getMontoChe() {
        return this.montoChe;
    }
    
    public void setMontoChe(double montoChe) {
        this.montoChe = montoChe;
    }
    public boolean isStaChe() {
        return this.staChe;
    }
    
    public void setStaChe(boolean staChe) {
        this.staChe = staChe;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }




}


