package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String rif;
     private Camion camion;
     private String codigo;
     private String raSo;
     private String direCli;
     private String telfCli;
     private String contCli;
     private String camionruta;
     private Set prestamos = new HashSet(0);
     private Set despachos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String rif, Camion camion, String codigo, String raSo, String direCli, String telfCli, String contCli) {
        this.rif = rif;
        this.camion = camion;
        this.codigo = codigo;
        this.raSo = raSo;
        this.direCli = direCli;
        this.telfCli = telfCli;
        this.contCli = contCli;
    }
    public Cliente(String rif, Camion camion, String codigo, String raSo, String direCli, String telfCli, String contCli, Set prestamos, Set despachos) {
       this.rif = rif;
       this.camion = camion;
       this.codigo = codigo;
       this.raSo = raSo;
       this.direCli = direCli;
       this.telfCli = telfCli;
       this.contCli = contCli;
       this.prestamos = prestamos;
       this.despachos = despachos;
    }
   
    public String getRif() {
        return this.rif;
    }
    
    public void setRif(String rif) {
        this.rif = rif;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getRaSo() {
        return this.raSo;
    }
    
    public void setRaSo(String raSo) {
        this.raSo = raSo;
    }
    public String getDireCli() {
        return this.direCli;
    }
    
    public void setDireCli(String direCli) {
        this.direCli = direCli;
    }
    public String getTelfCli() {
        return this.telfCli;
    }
    
    public void setTelfCli(String telfCli) {
        this.telfCli = telfCli;
    }
    public String getContCli() {
        return this.contCli;
    }
    
    public void setContCli(String contCli) {
        this.contCli = contCli;
    }
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }
    public Set getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set despachos) {
        this.despachos = despachos;
    }

    public String getCamionruta() {
        return camionruta;
    }

    public void setCamionruta(String camionruta) {
        this.camionruta = camionruta;
    }




}


