package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto  implements java.io.Serializable {


     private Integer idconcepto;
     private String conceptoPago;
     private Set detalleCons = new HashSet(0);

    public Concepto() {
    }

	
    public Concepto(String conceptoPago) {
        this.conceptoPago = conceptoPago;
    }
    public Concepto(String conceptoPago, Set detalleCons) {
       this.conceptoPago = conceptoPago;
       this.detalleCons = detalleCons;
    }
   
    public Integer getIdconcepto() {
        return this.idconcepto;
    }
    
    public void setIdconcepto(Integer idconcepto) {
        this.idconcepto = idconcepto;
    }
    public String getConceptoPago() {
        return this.conceptoPago;
    }
    
    public void setConceptoPago(String conceptoPago) {
        this.conceptoPago = conceptoPago;
    }
    public Set getDetalleCons() {
        return this.detalleCons;
    }
    
    public void setDetalleCons(Set detalleCons) {
        this.detalleCons = detalleCons;
    }




}


