package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Control generated by hbm2java
 */
public class Control  implements java.io.Serializable {


     private Integer idcontrol;
     private String ip;
     private String hostName;

    public Control() {
    }

    public Control(String ip, String hostName) {
       this.ip = ip;
       this.hostName = hostName;
    }
   
    public Integer getIdcontrol() {
        return this.idcontrol;
    }
    
    public void setIdcontrol(Integer idcontrol) {
        this.idcontrol = idcontrol;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }




}


