package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * ConVa generated by hbm2java
 */
public class ConVa  implements java.io.Serializable {


     private Integer idconVa;
     private Vacaciones vacaciones;
     private String conVacol;
     private double moVa;

    public ConVa() {
    }

    public ConVa(Vacaciones vacaciones, String conVacol, double moVa) {
       this.vacaciones = vacaciones;
       this.conVacol = conVacol;
       this.moVa = moVa;
    }
   
    public Integer getIdconVa() {
        return this.idconVa;
    }
    
    public void setIdconVa(Integer idconVa) {
        this.idconVa = idconVa;
    }
    public Vacaciones getVacaciones() {
        return this.vacaciones;
    }
    
    public void setVacaciones(Vacaciones vacaciones) {
        this.vacaciones = vacaciones;
    }
    public String getConVacol() {
        return this.conVacol;
    }
    
    public void setConVacol(String conVacol) {
        this.conVacol = conVacol;
    }
    public double getMoVa() {
        return this.moVa;
    }
    
    public void setMoVa(double moVa) {
        this.moVa = moVa;
    }




}


