package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Credito generated by hbm2java
 */
public class Credito  implements java.io.Serializable {


     private Integer idCre;
     private Despacho despacho;
     private boolean staCre;
     private Set cancels = new HashSet(0);

    public Credito() {
    }

	
    public Credito(Despacho despacho, boolean staCre) {
        this.despacho = despacho;
        this.staCre = staCre;
    }
    public Credito(Despacho despacho, boolean staCre, Set cancels) {
       this.despacho = despacho;
       this.staCre = staCre;
       this.cancels = cancels;
    }
   
    public Integer getIdCre() {
        return this.idCre;
    }
    
    public void setIdCre(Integer idCre) {
        this.idCre = idCre;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public boolean isStaCre() {
        return this.staCre;
    }
    
    public void setStaCre(boolean staCre) {
        this.staCre = staCre;
    }
    public Set getCancels() {
        return this.cancels;
    }
    
    public void setCancels(Set cancels) {
        this.cancels = cancels;
    }




}


