package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Deducciones generated by hbm2java
 */
public class Deducciones  implements java.io.Serializable {


     private Integer iddeducciones;
     private FeNo feNo;
     private String dedu;
     private double moDedu;

    public Deducciones() {
    }

    public Deducciones(FeNo feNo, String dedu, double moDedu) {
       this.feNo = feNo;
       this.dedu = dedu;
       this.moDedu = moDedu;
    }
   
    public Integer getIddeducciones() {
        return this.iddeducciones;
    }
    
    public void setIddeducciones(Integer iddeducciones) {
        this.iddeducciones = iddeducciones;
    }
    public FeNo getFeNo() {
        return this.feNo;
    }
    
    public void setFeNo(FeNo feNo) {
        this.feNo = feNo;
    }
    public String getDedu() {
        return this.dedu;
    }
    
    public void setDedu(String dedu) {
        this.dedu = dedu;
    }
    public double getMoDedu() {
        return this.moDedu;
    }
    
    public void setMoDedu(double moDedu) {
        this.moDedu = moDedu;
    }




}


