package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Descarga generated by hbm2java
 */
public class Descarga  implements java.io.Serializable {


     private Integer iddescarga;
     private String tipoDesc;
     private Date fechaDescarga;
     private int cantiDesca;
     private String caDescarga;
     private String usuDescargo;
     private String moDescargo;

    public Descarga() {
    }

    public Descarga(String tipoDesc, Date fechaDescarga, int cantiDesca, String caDescarga, String usuDescargo, String moDescargo) {
       this.tipoDesc = tipoDesc;
       this.fechaDescarga = fechaDescarga;
       this.cantiDesca = cantiDesca;
       this.caDescarga = caDescarga;
       this.usuDescargo = usuDescargo;
       this.moDescargo = moDescargo;
    }
   
    public Integer getIddescarga() {
        return this.iddescarga;
    }
    
    public void setIddescarga(Integer iddescarga) {
        this.iddescarga = iddescarga;
    }
    public String getTipoDesc() {
        return this.tipoDesc;
    }
    
    public void setTipoDesc(String tipoDesc) {
        this.tipoDesc = tipoDesc;
    }
    public Date getFechaDescarga() {
        return this.fechaDescarga;
    }
    
    public void setFechaDescarga(Date fechaDescarga) {
        this.fechaDescarga = fechaDescarga;
    }
    public int getCantiDesca() {
        return this.cantiDesca;
    }
    
    public void setCantiDesca(int cantiDesca) {
        this.cantiDesca = cantiDesca;
    }
    public String getCaDescarga() {
        return this.caDescarga;
    }
    
    public void setCaDescarga(String caDescarga) {
        this.caDescarga = caDescarga;
    }
    public String getUsuDescargo() {
        return this.usuDescargo;
    }
    
    public void setUsuDescargo(String usuDescargo) {
        this.usuDescargo = usuDescargo;
    }
    public String getMoDescargo() {
        return this.moDescargo;
    }
    
    public void setMoDescargo(String moDescargo) {
        this.moDescargo = moDescargo;
    }




}


