package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Despacho generated by hbm2java
 */
public class Despacho  implements java.io.Serializable {


     private Integer coDesp;
     private Camion camion;
     private Cliente cliente;
     private Date fechaDes;
     private int montoDes;
     private String nroFac;
     private String nroCon;
     private int facturar;
     private Set cheques = new HashSet(0);
     private Set facturas = new HashSet(0);
     private Set salidas = new HashSet(0);
     private Set pagoses = new HashSet(0);
     private Set creditos = new HashSet(0);

    public Despacho() {
    }

	
    public Despacho(Camion camion, Cliente cliente, Date fechaDes, int montoDes, String nroFac, String nroCon, int facturar) {
        this.camion = camion;
        this.cliente = cliente;
        this.fechaDes = fechaDes;
        this.montoDes = montoDes;
        this.nroFac = nroFac;
        this.nroCon = nroCon;
        this.facturar = facturar;
    }
    public Despacho(Camion camion, Cliente cliente, Date fechaDes, int montoDes, String nroFac, String nroCon, int facturar, Set cheques, Set facturas, Set salidas, Set pagoses, Set creditos) {
       this.camion = camion;
       this.cliente = cliente;
       this.fechaDes = fechaDes;
       this.montoDes = montoDes;
       this.nroFac = nroFac;
       this.nroCon = nroCon;
       this.facturar = facturar;
       this.cheques = cheques;
       this.facturas = facturas;
       this.salidas = salidas;
       this.pagoses = pagoses;
       this.creditos = creditos;
    }
   
    public Integer getCoDesp() {
        return this.coDesp;
    }
    
    public void setCoDesp(Integer coDesp) {
        this.coDesp = coDesp;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaDes() {
        return this.fechaDes;
    }
    
    public void setFechaDes(Date fechaDes) {
        this.fechaDes = fechaDes;
    }
    public int getMontoDes() {
        return this.montoDes;
    }
    
    public void setMontoDes(int montoDes) {
        this.montoDes = montoDes;
    }
    public String getNroFac() {
        return this.nroFac;
    }
    
    public void setNroFac(String nroFac) {
        this.nroFac = nroFac;
    }
    public String getNroCon() {
        return this.nroCon;
    }
    
    public void setNroCon(String nroCon) {
        this.nroCon = nroCon;
    }
    public int getFacturar() {
        return this.facturar;
    }
    
    public void setFacturar(int facturar) {
        this.facturar = facturar;
    }
    public Set getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Set cheques) {
        this.cheques = cheques;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }
    public Set getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Set creditos) {
        this.creditos = creditos;
    }




}


