package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetalleAde generated by hbm2java
 */
public class DetalleAde  implements java.io.Serializable {


     private Integer iddetalleAde;
     private Prestaciones prestaciones;
     private String motivo;
     private String porcentaje;
     private Date fecAdelanto;

    public DetalleAde() {
    }

    public DetalleAde(Prestaciones prestaciones, String motivo, String porcentaje, Date fecAdelanto) {
       this.prestaciones = prestaciones;
       this.motivo = motivo;
       this.porcentaje = porcentaje;
       this.fecAdelanto = fecAdelanto;
    }
   
    public Integer getIddetalleAde() {
        return this.iddetalleAde;
    }
    
    public void setIddetalleAde(Integer iddetalleAde) {
        this.iddetalleAde = iddetalleAde;
    }
    public Prestaciones getPrestaciones() {
        return this.prestaciones;
    }
    
    public void setPrestaciones(Prestaciones prestaciones) {
        this.prestaciones = prestaciones;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(String porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Date getFecAdelanto() {
        return this.fecAdelanto;
    }
    
    public void setFecAdelanto(Date fecAdelanto) {
        this.fecAdelanto = fecAdelanto;
    }




}


