package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DevolucionDes generated by hbm2java
 */
public class DevolucionDes  implements java.io.Serializable {


     private Integer iddevolucion;
     private String codDes;
     private String camionDes;
     private String feDes;
     private String cliDes;
     private String feDevo;
     private String usuDevo;
     private Set cans = new HashSet(0);

    public DevolucionDes() {
    }

	
    public DevolucionDes(String codDes, String camionDes, String feDes, String cliDes, String feDevo, String usuDevo) {
        this.codDes = codDes;
        this.camionDes = camionDes;
        this.feDes = feDes;
        this.cliDes = cliDes;
        this.feDevo = feDevo;
        this.usuDevo = usuDevo;
    }
    public DevolucionDes(String codDes, String camionDes, String feDes, String cliDes, String feDevo, String usuDevo, Set cans) {
       this.codDes = codDes;
       this.camionDes = camionDes;
       this.feDes = feDes;
       this.cliDes = cliDes;
       this.feDevo = feDevo;
       this.usuDevo = usuDevo;
       this.cans = cans;
    }
   
    public Integer getIddevolucion() {
        return this.iddevolucion;
    }
    
    public void setIddevolucion(Integer iddevolucion) {
        this.iddevolucion = iddevolucion;
    }
    public String getCodDes() {
        return this.codDes;
    }
    
    public void setCodDes(String codDes) {
        this.codDes = codDes;
    }
    public String getCamionDes() {
        return this.camionDes;
    }
    
    public void setCamionDes(String camionDes) {
        this.camionDes = camionDes;
    }
    public String getFeDes() {
        return this.feDes;
    }
    
    public void setFeDes(String feDes) {
        this.feDes = feDes;
    }
    public String getCliDes() {
        return this.cliDes;
    }
    
    public void setCliDes(String cliDes) {
        this.cliDes = cliDes;
    }
    public String getFeDevo() {
        return this.feDevo;
    }
    
    public void setFeDevo(String feDevo) {
        this.feDevo = feDevo;
    }
    public String getUsuDevo() {
        return this.usuDevo;
    }
    
    public void setUsuDevo(String usuDevo) {
        this.usuDevo = usuDevo;
    }
    public Set getCans() {
        return this.cans;
    }
    
    public void setCans(Set cans) {
        this.cans = cans;
    }




}


