package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DevRece generated by hbm2java
 */
public class DevRece  implements java.io.Serializable {


     private Integer iddevRece;
     private String codRe;
     private String camRe;
     private String feDevRe;
     private String usuDevRe;
     private Set detalleRes = new HashSet(0);

    public DevRece() {
    }

	
    public DevRece(String codRe, String camRe, String feDevRe, String usuDevRe) {
        this.codRe = codRe;
        this.camRe = camRe;
        this.feDevRe = feDevRe;
        this.usuDevRe = usuDevRe;
    }
    public DevRece(String codRe, String camRe, String feDevRe, String usuDevRe, Set detalleRes) {
       this.codRe = codRe;
       this.camRe = camRe;
       this.feDevRe = feDevRe;
       this.usuDevRe = usuDevRe;
       this.detalleRes = detalleRes;
    }
   
    public Integer getIddevRece() {
        return this.iddevRece;
    }
    
    public void setIddevRece(Integer iddevRece) {
        this.iddevRece = iddevRece;
    }
    public String getCodRe() {
        return this.codRe;
    }
    
    public void setCodRe(String codRe) {
        this.codRe = codRe;
    }
    public String getCamRe() {
        return this.camRe;
    }
    
    public void setCamRe(String camRe) {
        this.camRe = camRe;
    }
    public String getFeDevRe() {
        return this.feDevRe;
    }
    
    public void setFeDevRe(String feDevRe) {
        this.feDevRe = feDevRe;
    }
    public String getUsuDevRe() {
        return this.usuDevRe;
    }
    
    public void setUsuDevRe(String usuDevRe) {
        this.usuDevRe = usuDevRe;
    }
    public Set getDetalleRes() {
        return this.detalleRes;
    }
    
    public void setDetalleRes(Set detalleRes) {
        this.detalleRes = detalleRes;
    }




}


