package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Eliminar generated by hbm2java
 */
public class Eliminar  implements java.io.Serializable {


     private Integer ideliminar;
     private String usuEli;
     private Date fecEli;
     private int idFa;
     private String ceduFi;
     private double montoEli;

    public Eliminar() {
    }

    public Eliminar(String usuEli, Date fecEli, int idFa, String ceduFi, double montoEli) {
       this.usuEli = usuEli;
       this.fecEli = fecEli;
       this.idFa = idFa;
       this.ceduFi = ceduFi;
       this.montoEli = montoEli;
    }
   
    public Integer getIdeliminar() {
        return this.ideliminar;
    }
    
    public void setIdeliminar(Integer ideliminar) {
        this.ideliminar = ideliminar;
    }
    public String getUsuEli() {
        return this.usuEli;
    }
    
    public void setUsuEli(String usuEli) {
        this.usuEli = usuEli;
    }
    public Date getFecEli() {
        return this.fecEli;
    }
    
    public void setFecEli(Date fecEli) {
        this.fecEli = fecEli;
    }
    public int getIdFa() {
        return this.idFa;
    }
    
    public void setIdFa(int idFa) {
        this.idFa = idFa;
    }
    public String getCeduFi() {
        return this.ceduFi;
    }
    
    public void setCeduFi(String ceduFi) {
        this.ceduFi = ceduFi;
    }
    public double getMontoEli() {
        return this.montoEli;
    }
    
    public void setMontoEli(double montoEli) {
        this.montoEli = montoEli;
    }




}


