package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String cedula;
     private Cargo cargo;
     private String nombEmp;
     private String apeEmp;
     private String direEmp;
     private String telfEmp;
     private Date ingreso;
     private boolean status;
     private Set ahorros = new HashSet(0);
     private Set feNos = new HashSet(0);
     private Set entregaAhorros = new HashSet(0);
     private Set vacacioneses = new HashSet(0);
     private Set vales = new HashSet(0);
     private Set utilidads = new HashSet(0);
     private Set financiars = new HashSet(0);
     private Set sueldos = new HashSet(0);
     private Set prestacioneses = new HashSet(0);
     private Set empls = new HashSet(0);
     private Set liquidars = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String cedula, Cargo cargo, String nombEmp, String apeEmp, String direEmp, String telfEmp, Date ingreso, boolean status) {
        this.cedula = cedula;
        this.cargo = cargo;
        this.nombEmp = nombEmp;
        this.apeEmp = apeEmp;
        this.direEmp = direEmp;
        this.telfEmp = telfEmp;
        this.ingreso = ingreso;
        this.status = status;
    }
    public Empleado(String cedula, Cargo cargo, String nombEmp, String apeEmp, String direEmp, String telfEmp, Date ingreso, boolean status, Set ahorros, Set feNos, Set entregaAhorros, Set vacacioneses, Set vales, Set utilidads, Set financiars, Set sueldos, Set prestacioneses, Set empls, Set liquidars) {
       this.cedula = cedula;
       this.cargo = cargo;
       this.nombEmp = nombEmp;
       this.apeEmp = apeEmp;
       this.direEmp = direEmp;
       this.telfEmp = telfEmp;
       this.ingreso = ingreso;
       this.status = status;
       this.ahorros = ahorros;
       this.feNos = feNos;
       this.entregaAhorros = entregaAhorros;
       this.vacacioneses = vacacioneses;
       this.vales = vales;
       this.utilidads = utilidads;
       this.financiars = financiars;
       this.sueldos = sueldos;
       this.prestacioneses = prestacioneses;
       this.empls = empls;
       this.liquidars = liquidars;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNombEmp() {
        return this.nombEmp;
    }
    
    public void setNombEmp(String nombEmp) {
        this.nombEmp = nombEmp;
    }
    public String getApeEmp() {
        return this.apeEmp;
    }
    
    public void setApeEmp(String apeEmp) {
        this.apeEmp = apeEmp;
    }
    public String getDireEmp() {
        return this.direEmp;
    }
    
    public void setDireEmp(String direEmp) {
        this.direEmp = direEmp;
    }
    public String getTelfEmp() {
        return this.telfEmp;
    }
    
    public void setTelfEmp(String telfEmp) {
        this.telfEmp = telfEmp;
    }
    public Date getIngreso() {
        return this.ingreso;
    }
    
    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getAhorros() {
        return this.ahorros;
    }
    
    public void setAhorros(Set ahorros) {
        this.ahorros = ahorros;
    }
    public Set getFeNos() {
        return this.feNos;
    }
    
    public void setFeNos(Set feNos) {
        this.feNos = feNos;
    }
    public Set getEntregaAhorros() {
        return this.entregaAhorros;
    }
    
    public void setEntregaAhorros(Set entregaAhorros) {
        this.entregaAhorros = entregaAhorros;
    }
    public Set getVacacioneses() {
        return this.vacacioneses;
    }
    
    public void setVacacioneses(Set vacacioneses) {
        this.vacacioneses = vacacioneses;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }
    public Set getUtilidads() {
        return this.utilidads;
    }
    
    public void setUtilidads(Set utilidads) {
        this.utilidads = utilidads;
    }
    public Set getFinanciars() {
        return this.financiars;
    }
    
    public void setFinanciars(Set financiars) {
        this.financiars = financiars;
    }
    public Set getSueldos() {
        return this.sueldos;
    }
    
    public void setSueldos(Set sueldos) {
        this.sueldos = sueldos;
    }
    public Set getPrestacioneses() {
        return this.prestacioneses;
    }
    
    public void setPrestacioneses(Set prestacioneses) {
        this.prestacioneses = prestacioneses;
    }
    public Set getEmpls() {
        return this.empls;
    }
    
    public void setEmpls(Set empls) {
        this.empls = empls;
    }
    public Set getLiquidars() {
        return this.liquidars;
    }
    
    public void setLiquidars(Set liquidars) {
        this.liquidars = liquidars;
    }




}


