package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Entrega generated by hbm2java
 */
public class Entrega  implements java.io.Serializable {


     private Integer identrega;
     private Producto producto;
     private Recepcion recepcion;
     private int cantEntra;

    public Entrega() {
    }

    public Entrega(Producto producto, Recepcion recepcion, int cantEntra) {
       this.producto = producto;
       this.recepcion = recepcion;
       this.cantEntra = cantEntra;
    }
   
    public Integer getIdentrega() {
        return this.identrega;
    }
    
    public void setIdentrega(Integer identrega) {
        this.identrega = identrega;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Recepcion getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Recepcion recepcion) {
        this.recepcion = recepcion;
    }
    public int getCantEntra() {
        return this.cantEntra;
    }
    
    public void setCantEntra(int cantEntra) {
        this.cantEntra = cantEntra;
    }




}


