package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FeNo generated by hbm2java
 */
public class FeNo  implements java.io.Serializable {


     private Integer idfeNo;
     private Empleado empleado;
     private String feDesde;
     private String feHasta;
     private String feNomina;
     private Set comisions = new HashSet(0);
     private Set nominas = new HashSet(0);
     private Set deduccioneses = new HashSet(0);

    public FeNo() {
    }

	
    public FeNo(Empleado empleado, String feDesde, String feHasta, String feNomina) {
        this.empleado = empleado;
        this.feDesde = feDesde;
        this.feHasta = feHasta;
        this.feNomina = feNomina;
    }
    public FeNo(Empleado empleado, String feDesde, String feHasta, String feNomina, Set comisions, Set nominas, Set deduccioneses) {
       this.empleado = empleado;
       this.feDesde = feDesde;
       this.feHasta = feHasta;
       this.feNomina = feNomina;
       this.comisions = comisions;
       this.nominas = nominas;
       this.deduccioneses = deduccioneses;
    }
   
    public Integer getIdfeNo() {
        return this.idfeNo;
    }
    
    public void setIdfeNo(Integer idfeNo) {
        this.idfeNo = idfeNo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getFeDesde() {
        return this.feDesde;
    }
    
    public void setFeDesde(String feDesde) {
        this.feDesde = feDesde;
    }
    public String getFeHasta() {
        return this.feHasta;
    }
    
    public void setFeHasta(String feHasta) {
        this.feHasta = feHasta;
    }
    public String getFeNomina() {
        return this.feNomina;
    }
    
    public void setFeNomina(String feNomina) {
        this.feNomina = feNomina;
    }
    public Set getComisions() {
        return this.comisions;
    }
    
    public void setComisions(Set comisions) {
        this.comisions = comisions;
    }
    public Set getNominas() {
        return this.nominas;
    }
    
    public void setNominas(Set nominas) {
        this.nominas = nominas;
    }
    public Set getDeduccioneses() {
        return this.deduccioneses;
    }
    
    public void setDeduccioneses(Set deduccioneses) {
        this.deduccioneses = deduccioneses;
    }




}


