package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * FidePolar generated by hbm2java
 */
public class FidePolar  implements java.io.Serializable {


     private Integer idfidePolar;
     private Recepcion recepcion;
     private double monto;

    public FidePolar() {
    }

    public FidePolar(Recepcion recepcion, double monto) {
       this.recepcion = recepcion;
       this.monto = monto;
    }
   
    public Integer getIdfidePolar() {
        return this.idfidePolar;
    }
    
    public void setIdfidePolar(Integer idfidePolar) {
        this.idfidePolar = idfidePolar;
    }
    public Recepcion getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Recepcion recepcion) {
        this.recepcion = recepcion;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }




}


