package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gastos generated by hbm2java
 */
public class Gastos  implements java.io.Serializable {


     private Integer idgastos;
     private Camion camion;
     private double toGa;
     private String descripcion;
     private Date fechaGa;
     private String nroFacGa;

    public Gastos() {
    }

    public Gastos(Camion camion, double toGa, String descripcion, Date fechaGa, String nroFacGa) {
       this.camion = camion;
       this.toGa = toGa;
       this.descripcion = descripcion;
       this.fechaGa = fechaGa;
       this.nroFacGa = nroFacGa;
    }
   
    public Integer getIdgastos() {
        return this.idgastos;
    }
    
    public void setIdgastos(Integer idgastos) {
        this.idgastos = idgastos;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public double getToGa() {
        return this.toGa;
    }
    
    public void setToGa(double toGa) {
        this.toGa = toGa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaGa() {
        return this.fechaGa;
    }
    
    public void setFechaGa(Date fechaGa) {
        this.fechaGa = fechaGa;
    }
    public String getNroFacGa() {
        return this.nroFacGa;
    }
    
    public void setNroFacGa(String nroFacGa) {
        this.nroFacGa = nroFacGa;
    }




}


