package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Manual generated by hbm2java
 */
public class Manual  implements java.io.Serializable {


     private Integer idManual;
     private Producto producto;
     private int cantMa;
     private Date feMa;

    public Manual() {
    }

    public Manual(Producto producto, int cantMa, Date feMa) {
       this.producto = producto;
       this.cantMa = cantMa;
       this.feMa = feMa;
    }
   
    public Integer getIdManual() {
        return this.idManual;
    }
    
    public void setIdManual(Integer idManual) {
        this.idManual = idManual;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantMa() {
        return this.cantMa;
    }
    
    public void setCantMa(int cantMa) {
        this.cantMa = cantMa;
    }
    public Date getFeMa() {
        return this.feMa;
    }
    
    public void setFeMa(Date feMa) {
        this.feMa = feMa;
    }




}


