package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Nomina generated by hbm2java
 */
public class Nomina  implements java.io.Serializable {


     private Integer idnomina;
     private FeNo feNo;
     private String conNo;
     private double montoNo;

    public Nomina() {
    }

    public Nomina(FeNo feNo, String conNo, double montoNo) {
       this.feNo = feNo;
       this.conNo = conNo;
       this.montoNo = montoNo;
    }
   
    public Integer getIdnomina() {
        return this.idnomina;
    }
    
    public void setIdnomina(Integer idnomina) {
        this.idnomina = idnomina;
    }
    public FeNo getFeNo() {
        return this.feNo;
    }
    
    public void setFeNo(FeNo feNo) {
        this.feNo = feNo;
    }
    public String getConNo() {
        return this.conNo;
    }
    
    public void setConNo(String conNo) {
        this.conNo = conNo;
    }
    public double getMontoNo() {
        return this.montoNo;
    }
    
    public void setMontoNo(double montoNo) {
        this.montoNo = montoNo;
    }




}


