package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos  implements java.io.Serializable {


     private Integer idpagos;
     private Despacho despacho;
     private Date fechaPa;
     private int monto;

    public Pagos() {
    }

    public Pagos(Despacho despacho, Date fechaPa, int monto) {
       this.despacho = despacho;
       this.fechaPa = fechaPa;
       this.monto = monto;
    }
   
    public Integer getIdpagos() {
        return this.idpagos;
    }
    
    public void setIdpagos(Integer idpagos) {
        this.idpagos = idpagos;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public Date getFechaPa() {
        return this.fechaPa;
    }
    
    public void setFechaPa(Date fechaPa) {
        this.fechaPa = fechaPa;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }




}


