package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * PrecioVa generated by hbm2java
 */
public class PrecioVa  implements java.io.Serializable {


     private Integer idprecioVa;
     private Presenta presenta;
     private double cosVa;

    public PrecioVa() {
    }

    public PrecioVa(Presenta presenta, double cosVa) {
       this.presenta = presenta;
       this.cosVa = cosVa;
    }
   
    public Integer getIdprecioVa() {
        return this.idprecioVa;
    }
    
    public void setIdprecioVa(Integer idprecioVa) {
        this.idprecioVa = idprecioVa;
    }
    public Presenta getPresenta() {
        return this.presenta;
    }
    
    public void setPresenta(Presenta presenta) {
        this.presenta = presenta;
    }
    public double getCosVa() {
        return this.cosVa;
    }
    
    public void setCosVa(double cosVa) {
        this.cosVa = cosVa;
    }




}


