package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Presenta generated by hbm2java
 */
public class Presenta  implements java.io.Serializable {


     private Integer idPre;
     private String presentacion;
     private Set precioVas = new HashSet(0);
     private Set productos = new HashSet(0);

    public Presenta() {
    }

	
    public Presenta(String presentacion) {
        this.presentacion = presentacion;
    }
    public Presenta(String presentacion, Set precioVas, Set productos) {
       this.presentacion = presentacion;
       this.precioVas = precioVas;
       this.productos = productos;
    }
   
    public Integer getIdPre() {
        return this.idPre;
    }
    
    public void setIdPre(Integer idPre) {
        this.idPre = idPre;
    }
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }
    public Set getPrecioVas() {
        return this.precioVas;
    }
    
    public void setPrecioVas(Set precioVas) {
        this.precioVas = precioVas;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


