package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer idprestamo;
     private Cliente cliente;
     private int cantPres;
     private int cantPresTe;

    public Prestamo() {
    }

    public Prestamo(Cliente cliente, int cantPres, int cantPresTe) {
       this.cliente = cliente;
       this.cantPres = cantPres;
       this.cantPresTe = cantPresTe;
    }
   
    public Integer getIdprestamo() {
        return this.idprestamo;
    }
    
    public void setIdprestamo(Integer idprestamo) {
        this.idprestamo = idprestamo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public int getCantPres() {
        return this.cantPres;
    }
    
    public void setCantPres(int cantPres) {
        this.cantPres = cantPres;
    }
    public int getCantPresTe() {
        return this.cantPresTe;
    }
    
    public void setCantPresTe(int cantPresTe) {
        this.cantPresTe = cantPresTe;
    }




}


