package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prestaciones generated by hbm2java
 */
public class Prestaciones  implements java.io.Serializable {


     private Integer idprestaciones;
     private Empleado empleado;
     private String periodo;
     private String diAbo;
     private String diaAdi;
     private String TInte;
     private Date fechaAbono;
     private double adelanto;
     private double adelantoInt;
     private Set detalleAdes = new HashSet(0);

    public Prestaciones() {
    }

	
    public Prestaciones(Empleado empleado, String periodo, String diAbo, String diaAdi, String TInte, Date fechaAbono, double adelanto, double adelantoInt) {
        this.empleado = empleado;
        this.periodo = periodo;
        this.diAbo = diAbo;
        this.diaAdi = diaAdi;
        this.TInte = TInte;
        this.fechaAbono = fechaAbono;
        this.adelanto = adelanto;
        this.adelantoInt = adelantoInt;
    }
    public Prestaciones(Empleado empleado, String periodo, String diAbo, String diaAdi, String TInte, Date fechaAbono, double adelanto, double adelantoInt, Set detalleAdes) {
       this.empleado = empleado;
       this.periodo = periodo;
       this.diAbo = diAbo;
       this.diaAdi = diaAdi;
       this.TInte = TInte;
       this.fechaAbono = fechaAbono;
       this.adelanto = adelanto;
       this.adelantoInt = adelantoInt;
       this.detalleAdes = detalleAdes;
    }
   
    public Integer getIdprestaciones() {
        return this.idprestaciones;
    }
    
    public void setIdprestaciones(Integer idprestaciones) {
        this.idprestaciones = idprestaciones;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getDiAbo() {
        return this.diAbo;
    }
    
    public void setDiAbo(String diAbo) {
        this.diAbo = diAbo;
    }
    public String getDiaAdi() {
        return this.diaAdi;
    }
    
    public void setDiaAdi(String diaAdi) {
        this.diaAdi = diaAdi;
    }
    public String getTInte() {
        return this.TInte;
    }
    
    public void setTInte(String TInte) {
        this.TInte = TInte;
    }
    public Date getFechaAbono() {
        return this.fechaAbono;
    }
    
    public void setFechaAbono(Date fechaAbono) {
        this.fechaAbono = fechaAbono;
    }
    public double getAdelanto() {
        return this.adelanto;
    }
    
    public void setAdelanto(double adelanto) {
        this.adelanto = adelanto;
    }
    public double getAdelantoInt() {
        return this.adelantoInt;
    }
    
    public void setAdelantoInt(double adelantoInt) {
        this.adelantoInt = adelantoInt;
    }
    public Set getDetalleAdes() {
        return this.detalleAdes;
    }
    
    public void setDetalleAdes(Set detalleAdes) {
        this.detalleAdes = detalleAdes;
    }




}


