package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer codiPro;
     private Categoria categoria;
     private Presenta presenta;
     private Retorno retorno;
     private String denoPro;
     private double preDe;
     private double preMa;
     private double preCo;
     private Set almacens = new HashSet(0);
     private Set entregas = new HashSet(0);
     private Set manuals = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, Presenta presenta, Retorno retorno, String denoPro, double preDe, double preMa, double preCo) {
        this.categoria = categoria;
        this.presenta = presenta;
        this.retorno = retorno;
        this.denoPro = denoPro;
        this.preDe = preDe;
        this.preMa = preMa;
        this.preCo = preCo;
    }
    public Producto(Categoria categoria, Presenta presenta, Retorno retorno, String denoPro, double preDe, double preMa, double preCo, Set almacens, Set entregas, Set manuals) {
       this.categoria = categoria;
       this.presenta = presenta;
       this.retorno = retorno;
       this.denoPro = denoPro;
       this.preDe = preDe;
       this.preMa = preMa;
       this.preCo = preCo;
       this.almacens = almacens;
       this.entregas = entregas;
       this.manuals = manuals;
    }
   
    public Integer getCodiPro() {
        return this.codiPro;
    }
    
    public void setCodiPro(Integer codiPro) {
        this.codiPro = codiPro;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Presenta getPresenta() {
        return this.presenta;
    }
    
    public void setPresenta(Presenta presenta) {
        this.presenta = presenta;
    }
    public Retorno getRetorno() {
        return this.retorno;
    }
    
    public void setRetorno(Retorno retorno) {
        this.retorno = retorno;
    }
    public String getDenoPro() {
        return this.denoPro;
    }
    
    public void setDenoPro(String denoPro) {
        this.denoPro = denoPro;
    }
    public double getPreDe() {
        return this.preDe;
    }
    
    public void setPreDe(double preDe) {
        this.preDe = preDe;
    }
    public double getPreMa() {
        return this.preMa;
    }
    
    public void setPreMa(double preMa) {
        this.preMa = preMa;
    }
    public double getPreCo() {
        return this.preCo;
    }
    
    public void setPreCo(double preCo) {
        this.preCo = preCo;
    }
    public Set getAlmacens() {
        return this.almacens;
    }
    
    public void setAlmacens(Set almacens) {
        this.almacens = almacens;
    }
    public Set getEntregas() {
        return this.entregas;
    }
    
    public void setEntregas(Set entregas) {
        this.entregas = entregas;
    }
    public Set getManuals() {
        return this.manuals;
    }
    
    public void setManuals(Set manuals) {
        this.manuals = manuals;
    }




}


