package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recepcion generated by hbm2java
 */
public class Recepcion  implements java.io.Serializable {


     private String nroControl;
     private boolean staPaRecep;
     private Date fechaRece;
     private String nroFactura;
     private double montoRe;
     private Set proComs = new HashSet(0);
     private Set entregas = new HashSet(0);
     private Set uniReIvas = new HashSet(0);
     private Set UReceCas = new HashSet(0);
     private Set URePros = new HashSet(0);
     private Set uniRetes = new HashSet(0);
     private Set fidePolars = new HashSet(0);

    public Recepcion() {
    }

	
    public Recepcion(String nroControl, boolean staPaRecep, Date fechaRece, String nroFactura, double montoRe) {
        this.nroControl = nroControl;
        this.staPaRecep = staPaRecep;
        this.fechaRece = fechaRece;
        this.nroFactura = nroFactura;
        this.montoRe = montoRe;
    }
    public Recepcion(String nroControl, boolean staPaRecep, Date fechaRece, String nroFactura, double montoRe, Set proComs, Set entregas, Set uniReIvas, Set UReceCas, Set URePros, Set uniRetes, Set fidePolars) {
       this.nroControl = nroControl;
       this.staPaRecep = staPaRecep;
       this.fechaRece = fechaRece;
       this.nroFactura = nroFactura;
       this.montoRe = montoRe;
       this.proComs = proComs;
       this.entregas = entregas;
       this.uniReIvas = uniReIvas;
       this.UReceCas = UReceCas;
       this.URePros = URePros;
       this.uniRetes = uniRetes;
       this.fidePolars = fidePolars;
    }
   
    public String getNroControl() {
        return this.nroControl;
    }
    
    public void setNroControl(String nroControl) {
        this.nroControl = nroControl;
    }
    public boolean isStaPaRecep() {
        return this.staPaRecep;
    }
    
    public void setStaPaRecep(boolean staPaRecep) {
        this.staPaRecep = staPaRecep;
    }
    public Date getFechaRece() {
        return this.fechaRece;
    }
    
    public void setFechaRece(Date fechaRece) {
        this.fechaRece = fechaRece;
    }
    public String getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(String nroFactura) {
        this.nroFactura = nroFactura;
    }
    public double getMontoRe() {
        return this.montoRe;
    }
    
    public void setMontoRe(double montoRe) {
        this.montoRe = montoRe;
    }
    public Set getProComs() {
        return this.proComs;
    }
    
    public void setProComs(Set proComs) {
        this.proComs = proComs;
    }
    public Set getEntregas() {
        return this.entregas;
    }
    
    public void setEntregas(Set entregas) {
        this.entregas = entregas;
    }
    public Set getUniReIvas() {
        return this.uniReIvas;
    }
    
    public void setUniReIvas(Set uniReIvas) {
        this.uniReIvas = uniReIvas;
    }
    public Set getUReceCas() {
        return this.UReceCas;
    }
    
    public void setUReceCas(Set UReceCas) {
        this.UReceCas = UReceCas;
    }
    public Set getURePros() {
        return this.URePros;
    }
    
    public void setURePros(Set URePros) {
        this.URePros = URePros;
    }
    public Set getUniRetes() {
        return this.uniRetes;
    }
    
    public void setUniRetes(Set uniRetes) {
        this.uniRetes = uniRetes;
    }
    public Set getFidePolars() {
        return this.fidePolars;
    }
    
    public void setFidePolars(Set fidePolars) {
        this.fidePolars = fidePolars;
    }




}


