package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Retenciones generated by hbm2java
 */
public class Retenciones  implements java.io.Serializable {


     private Integer idretenciones;
     private double baseImponible;
     private double montoRetenido;
     private Date fechaRete;
     private Set uniReIvas = new HashSet(0);
     private Set uniRetes = new HashSet(0);

    public Retenciones() {
    }

	
    public Retenciones(double baseImponible, double montoRetenido, Date fechaRete) {
        this.baseImponible = baseImponible;
        this.montoRetenido = montoRetenido;
        this.fechaRete = fechaRete;
    }
    public Retenciones(double baseImponible, double montoRetenido, Date fechaRete, Set uniReIvas, Set uniRetes) {
       this.baseImponible = baseImponible;
       this.montoRetenido = montoRetenido;
       this.fechaRete = fechaRete;
       this.uniReIvas = uniReIvas;
       this.uniRetes = uniRetes;
    }
   
    public Integer getIdretenciones() {
        return this.idretenciones;
    }
    
    public void setIdretenciones(Integer idretenciones) {
        this.idretenciones = idretenciones;
    }
    public double getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(double baseImponible) {
        this.baseImponible = baseImponible;
    }
    public double getMontoRetenido() {
        return this.montoRetenido;
    }
    
    public void setMontoRetenido(double montoRetenido) {
        this.montoRetenido = montoRetenido;
    }
    public Date getFechaRete() {
        return this.fechaRete;
    }
    
    public void setFechaRete(Date fechaRete) {
        this.fechaRete = fechaRete;
    }
    public Set getUniReIvas() {
        return this.uniReIvas;
    }
    
    public void setUniReIvas(Set uniReIvas) {
        this.uniReIvas = uniReIvas;
    }
    public Set getUniRetes() {
        return this.uniRetes;
    }
    
    public void setUniRetes(Set uniRetes) {
        this.uniRetes = uniRetes;
    }




}


