package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Retorno generated by hbm2java
 */
public class Retorno  implements java.io.Serializable {


     private Integer idReto;
     private String tipoReto;
     private Set productos = new HashSet(0);

    public Retorno() {
    }

	
    public Retorno(String tipoReto) {
        this.tipoReto = tipoReto;
    }
    public Retorno(String tipoReto, Set productos) {
       this.tipoReto = tipoReto;
       this.productos = productos;
    }
   
    public Integer getIdReto() {
        return this.idReto;
    }
    
    public void setIdReto(Integer idReto) {
        this.idReto = idReto;
    }
    public String getTipoReto() {
        return this.tipoReto;
    }
    
    public void setTipoReto(String tipoReto) {
        this.tipoReto = tipoReto;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


