package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private Integer idsalida;
     private Almacen almacen;
     private Despacho despacho;
     private int cantSale;
     private double precSalePro;

    public Salida() {
    }

    public Salida(Almacen almacen, Despacho despacho, int cantSale, double precSalePro) {
       this.almacen = almacen;
       this.despacho = despacho;
       this.cantSale = cantSale;
       this.precSalePro = precSalePro;
    }
   
    public Integer getIdsalida() {
        return this.idsalida;
    }
    
    public void setIdsalida(Integer idsalida) {
        this.idsalida = idsalida;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public int getCantSale() {
        return this.cantSale;
    }
    
    public void setCantSale(int cantSale) {
        this.cantSale = cantSale;
    }
    public double getPrecSalePro() {
        return this.precSalePro;
    }
    
    public void setPrecSalePro(double precSalePro) {
        this.precSalePro = precSalePro;
    }




}


