package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Sueldo generated by hbm2java
 */
public class Sueldo  implements java.io.Serializable {


     private Integer idsueldo;
     private Empleado empleado;
     private double suBase;
     private double comi;
     private double porahorro;
     private double ahorroEmp;

    public Sueldo() {
    }

    public Sueldo(Empleado empleado, double suBase, double comi, double porahorro, double ahorroEmp) {
       this.empleado = empleado;
       this.suBase = suBase;
       this.comi = comi;
       this.porahorro = porahorro;
       this.ahorroEmp = ahorroEmp;
    }
   
    public Integer getIdsueldo() {
        return this.idsueldo;
    }
    
    public void setIdsueldo(Integer idsueldo) {
        this.idsueldo = idsueldo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public double getSuBase() {
        return this.suBase;
    }
    
    public void setSuBase(double suBase) {
        this.suBase = suBase;
    }
    public double getComi() {
        return this.comi;
    }
    
    public void setComi(double comi) {
        this.comi = comi;
    }
    public double getPorahorro() {
        return this.porahorro;
    }
    
    public void setPorahorro(double porahorro) {
        this.porahorro = porahorro;
    }
    public double getAhorroEmp() {
        return this.ahorroEmp;
    }
    
    public void setAhorroEmp(double ahorroEmp) {
        this.ahorroEmp = ahorroEmp;
    }




}


