package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private Integer idtipoPago;
     private String tipoP;
     private Set cancels = new HashSet(0);
     private Set facturas = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(String tipoP) {
        this.tipoP = tipoP;
    }
    public TipoPago(String tipoP, Set cancels, Set facturas) {
       this.tipoP = tipoP;
       this.cancels = cancels;
       this.facturas = facturas;
    }
   
    public Integer getIdtipoPago() {
        return this.idtipoPago;
    }
    
    public void setIdtipoPago(Integer idtipoPago) {
        this.idtipoPago = idtipoPago;
    }
    public String getTipoP() {
        return this.tipoP;
    }
    
    public void setTipoP(String tipoP) {
        this.tipoP = tipoP;
    }
    public Set getCancels() {
        return this.cancels;
    }
    
    public void setCancels(Set cancels) {
        this.cancels = cancels;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


