package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * UniReIva generated by hbm2java
 */
public class UniReIva  implements java.io.Serializable {


     private Integer iduniReIva;
     private Recepcion recepcion;
     private Retenciones retenciones;

    public UniReIva() {
    }

    public UniReIva(Recepcion recepcion, Retenciones retenciones) {
       this.recepcion = recepcion;
       this.retenciones = retenciones;
    }
   
    public Integer getIduniReIva() {
        return this.iduniReIva;
    }
    
    public void setIduniReIva(Integer iduniReIva) {
        this.iduniReIva = iduniReIva;
    }
    public Recepcion getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Recepcion recepcion) {
        this.recepcion = recepcion;
    }
    public Retenciones getRetenciones() {
        return this.retenciones;
    }
    
    public void setRetenciones(Retenciones retenciones) {
        this.retenciones = retenciones;
    }




}


