package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * UReceCa generated by hbm2java
 */
public class UReceCa  implements java.io.Serializable {


     private Integer iduReceCa;
     private Camion camion;
     private Recepcion recepcion;

    public UReceCa() {
    }

    public UReceCa(Camion camion, Recepcion recepcion) {
       this.camion = camion;
       this.recepcion = recepcion;
    }
   
    public Integer getIduReceCa() {
        return this.iduReceCa;
    }
    
    public void setIduReceCa(Integer iduReceCa) {
        this.iduReceCa = iduReceCa;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public Recepcion getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Recepcion recepcion) {
        this.recepcion = recepcion;
    }




}


