package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Ut generated by hbm2java
 */
public class Ut  implements java.io.Serializable {


     private Integer idut;
     private double valor;

    public Ut() {
    }

    public Ut(double valor) {
       this.valor = valor;
    }
   
    public Integer getIdut() {
        return this.idut;
    }
    
    public void setIdut(Integer idut) {
        this.idut = idut;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }




}


