package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Utilidad generated by hbm2java
 */
public class Utilidad  implements java.io.Serializable {


     private Integer idutilidad;
     private Empleado empleado;
     private Date fcha;
     private int meses;
     private double utilidadcol;
     private double salaUti;
     private double inces;
     private double pago;

    public Utilidad() {
    }

    public Utilidad(Empleado empleado, Date fcha, int meses, double utilidadcol, double salaUti, double inces, double pago) {
       this.empleado = empleado;
       this.fcha = fcha;
       this.meses = meses;
       this.utilidadcol = utilidadcol;
       this.salaUti = salaUti;
       this.inces = inces;
       this.pago = pago;
    }
   
    public Integer getIdutilidad() {
        return this.idutilidad;
    }
    
    public void setIdutilidad(Integer idutilidad) {
        this.idutilidad = idutilidad;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFcha() {
        return this.fcha;
    }
    
    public void setFcha(Date fcha) {
        this.fcha = fcha;
    }
    public int getMeses() {
        return this.meses;
    }
    
    public void setMeses(int meses) {
        this.meses = meses;
    }
    public double getUtilidadcol() {
        return this.utilidadcol;
    }
    
    public void setUtilidadcol(double utilidadcol) {
        this.utilidadcol = utilidadcol;
    }
    public double getSalaUti() {
        return this.salaUti;
    }
    
    public void setSalaUti(double salaUti) {
        this.salaUti = salaUti;
    }
    public double getInces() {
        return this.inces;
    }
    
    public void setInces(double inces) {
        this.inces = inces;
    }
    public double getPago() {
        return this.pago;
    }
    
    public void setPago(double pago) {
        this.pago = pago;
    }




}


