package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vacaciones generated by hbm2java
 */
public class Vacaciones  implements java.io.Serializable {


     private Integer idvacaciones;
     private Empleado empleado;
     private Date deVa;
     private Date haVa;
     private Set conVas = new HashSet(0);

    public Vacaciones() {
    }

	
    public Vacaciones(Empleado empleado, Date deVa, Date haVa) {
        this.empleado = empleado;
        this.deVa = deVa;
        this.haVa = haVa;
    }
    public Vacaciones(Empleado empleado, Date deVa, Date haVa, Set conVas) {
       this.empleado = empleado;
       this.deVa = deVa;
       this.haVa = haVa;
       this.conVas = conVas;
    }
   
    public Integer getIdvacaciones() {
        return this.idvacaciones;
    }
    
    public void setIdvacaciones(Integer idvacaciones) {
        this.idvacaciones = idvacaciones;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getDeVa() {
        return this.deVa;
    }
    
    public void setDeVa(Date deVa) {
        this.deVa = deVa;
    }
    public Date getHaVa() {
        return this.haVa;
    }
    
    public void setHaVa(Date haVa) {
        this.haVa = haVa;
    }
    public Set getConVas() {
        return this.conVas;
    }
    
    public void setConVas(Set conVas) {
        this.conVas = conVas;
    }




}


