package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1



/**
 * Vacios generated by hbm2java
 */
public class Vacios  implements java.io.Serializable {


     private Integer idvacios;
     private Camion camion;
     private int cantVa;
     private int preRe;

    public Vacios() {
    }

    public Vacios(Camion camion, int cantVa, int preRe) {
       this.camion = camion;
       this.cantVa = cantVa;
       this.preRe = preRe;
    }
   
    public Integer getIdvacios() {
        return this.idvacios;
    }
    
    public void setIdvacios(Integer idvacios) {
        this.idvacios = idvacios;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public int getCantVa() {
        return this.cantVa;
    }
    
    public void setCantVa(int cantVa) {
        this.cantVa = cantVa;
    }
    public int getPreRe() {
        return this.preRe;
    }
    
    public void setPreRe(int preRe) {
        this.preRe = preRe;
    }




}


