package com.solutionsDevelopers.Entidades;
// Generated 20/10/2018 09:47:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vale generated by hbm2java
 */
public class Vale  implements java.io.Serializable {


     private Integer idVale;
     private Empleado empleado;
     private double montoVale;
     private Date feVale;

    public Vale() {
    }

    public Vale(Empleado empleado, double montoVale, Date feVale) {
       this.empleado = empleado;
       this.montoVale = montoVale;
       this.feVale = feVale;
    }
   
    public Integer getIdVale() {
        return this.idVale;
    }
    
    public void setIdVale(Integer idVale) {
        this.idVale = idVale;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public double getMontoVale() {
        return this.montoVale;
    }
    
    public void setMontoVale(double montoVale) {
        this.montoVale = montoVale;
    }
    public Date getFeVale() {
        return this.feVale;
    }
    
    public void setFeVale(Date feVale) {
        this.feVale = feVale;
    }




}


